sudo: required
services:
 - docker



before_install:
 - docker build -t adityasharma369/react-test -f ./client/Dockerfile.dev ./client



script:
 - docker run adityasharma369/react-test npm test -- --coverage


after_success:
 - docker build -t adityasharma369/multi-client ./client
 - docker build -t adityasharma369/multi-ngnix ./ngnix
 - docker build -t adityasharma369/multi-server ./server
 - docker build -t adityasharma369/multi-worker ./worker
 #Docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Docker push
 - docker push adityasharma369/multi-client
 - docker push adityasharma369/multi-ngnix
#  - docker push adityasharma369/multi-server
#  - docker push adityasharma369/multi-worker